name: Build

name: Build

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      # Step 3: Install everything else from requirements.txt
      - name: Install from requirements
        run: |
          pip install -r requirements.txt

      # Step 5: Finally run your main script
      - name: Do the thing
        run: python main.py
