name: automailer # name of the workflow

on:
  workflow_dispatch: # manual trigger of the workflow (if not set you cannot trigger it manually)
  schedule:
    - cron: '0 2 * * 1-6' # At 06:00 on every day-of-week from Tuesday through Saturday

jobs: # the jobs that will run sequentially
  build:
    runs-on: self-hosted
    steps: 

      - name: checkout repo content
        uses: actions/checkout@v4 # checkout the repository content to github runner
    
      - name: Verify Python Version
        run: python --version  # install the python version needed

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: execute py script # run main.py
        env:
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
          SMTP_USER: ${{ secrets.SMTP_USER }}
          TO_EMAIL: ${{ secrets.TO_EMAIL }}
        run: python main.py
