name: Build

name: Build

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Check Python
        run: python --version

      # Step 1: Install python-dotenv separately
      - name: Install python-dotenv
        run: |
          pip install python-dotenv

      # Step 2: Debug step to see what got installed
      - name: Freeze Debug #1
        run: pip freeze

      # Step 3: Install everything else from requirements.txt
      - name: Install from requirements
        run: |
          pip install -r requirements.txt

      # Step 4: Another debug step to see all installed packages
      - name: Freeze Debug #2
        run: pip freeze

      # Step 5: Finally run your main script
      - name: Do the thing
        run: python main.py
