name: Build

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  # or whatever version you need

      - name: Check python
        run: python --version

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Check installed packages
        run: pip freeze


      - name: Do the thing
        run: python main.py
